spring:
  datasource:
    url: jdbc:mysql://localhost:8080/travel_on_na?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: cho49109733

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 25844706303-11mshui5o955um75du0nkbapsnt5ovi9.apps.googleusercontent.com
            client-secret: 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
jwt:
  secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  expiration: 3600000  # 1시간
  refresh-token:
      expiration: 2592000000  # 30일
